---
title: "EDA - Visualizaciones"
output: html_notebook
---

# Introducción
```{r}
rm(list=ls())
gc()

library(readr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(tsibble)
library(feasts)
library(prophet)


# agrupamientos
group_cols_prod = c( "anio", "mes", 
                "cuenca", "areayacimiento" , "areapermisoconcesion",
                "clasificacion", "tipo_de_recurso" ,"tipopozo", "tipoextraccion",
                "proyecto",
                "concepto")

# función de agregacion
agregacion <- function(x) {
  x %>% 
    summarise(prod_pet = sum(prod_pet, na.rm = T),
           prod_gas = sum(prod_gas, na.rm = T),
           prod_agua = sum(prod_agua, na.rm = T),
           tef_avg = mean(tef_avg, na.rm = T),
           vida_util_avg = mean(vida_util_avg, na.rm = T),
           inversion_explotacion = sum(inversion_explotacion, na.rm = T),
           inversion_exploracion = sum(inversion_exploracion, na.rm = T),
           precio_interno_crudo = mean(precio_interno_crudo, na.rm = T),
           precio_interno_gas = mean(precio_interno_gas, na.rm = T),
           riesgo_pais = mean(riesgo_pais, na.rm = T)
            )
}

```

# Datos
```{r}

#datos originales
data <- read_csv("../data/resultados/dataset_2013a2020.csv", 
    locale = locale(encoding = "ISO-8859-1")) %>%
  filter(anio %in% c(2016:2019)) %>%                     # filtro años para mayor velocidad
  mutate(fecha =  yearmonth(paste(anio, mes, sep="/")) ,
         n_dias = days_in_month(fecha),
         prod_pet = prod_pet/n_dias,
         prod_gas = prod_gas/n_dias,
         prod_agua = prod_agua/n_dias) %>%           # CONVERSION A UNIDADES DIARIAS
  select(-n_dias)
  # group_by_at(group_cols_prod ) %>% 
  # agregacion()

# todos los datos agrupados por el vector de agrupamiento
data_time = data %>%      #SOLO SIRVE PARA DATOS DE PRODUCCION
  as_tsibble(index = fecha, 
             key =  all_of(group_cols_prod))

# agregados por cuenca
data_cuenca_time = data %>% 
  distinct(fecha, cuenca,areayacimiento, areapermisoconcesion, .keep_all = T ) %>%
  group_by(fecha, cuenca ) %>%
  agregacion() %>% 
  as_tsibble(index = fecha, 
             key =  cuenca)

# PARA INVERSION
inv_cuenca = data %>% 
  distinct(anio, concepto, cuenca, areapermisoconcesion, .keep_all = T ) %>% 
  group_by(anio, cuenca) %>% 
  agregacion() %>% 
  as_tsibble(index = anio, 
             key =  all_of(c("cuenca")))

inv_tot = data %>%
  distinct(anio, concepto,  areapermisoconcesion, .keep_all = T ) %>%
  group_by(anio) %>%
  agregacion() %>%
  as_tsibble(index = anio)

# PARA PRECIOS
precios_cuenca = data %>% 
  distinct(fecha, cuenca, .keep_all = T ) %>% 
  group_by(fecha, cuenca) %>% 
  agregacion() %>% 
  as_tsibble(index = fecha, 
             key =  all_of(c("cuenca")))

precios_tot = data %>%
  distinct(fecha, cuenca, .keep_all = T ) %>%
  group_by(fecha) %>%
  agregacion() %>%
  as_tsibble(index = fecha)
  
  
# rm(data)
gc()

# agregacion totales por mes
prod_tot = data_time %>%   #NO SIRVE PARA INVERSION ni PRECIOS
  agregacion()





```

# EDA
## Producción
```{r}
# TOTAL
autoplot(prod_tot, prod_pet)+
  labs(title = "Producción de petróleo crudo",
       subtitle = "Argentina",
       y = "m3")

autoplot(prod_tot, prod_gas)+
  labs(title = "Producción de gas natural",
       subtitle = "Argentina",
       y = "Mm3")

# CUENCA
autoplot(data_cuenca_time, prod_pet)+
  labs(title = "Producción de petróleo crudo",
       subtitle = "Argentina",
       y = "m3")+theme(legend.position = "bottom")

autoplot(data_cuenca_time, prod_gas)+
  labs(title = "Producción de gas natural",
       subtitle = "Argentina",
       y = "Mm3")


```
### Con suavizado
```{r}
ggplot(prod_tot, aes(fecha, prod_pet)) + geom_point(color='forestgreen') + geom_smooth() + theme_bw() + labs(title='Producción de petróleo: Suavizado')

ggplot(prod_tot, aes(fecha, prod_gas)) + geom_point(color='forestgreen') + geom_smooth() + theme_bw() + labs(title='Producción de gas: Suavizado')

```


## Inversión
```{r}
# TOTAL
autoplot(inv_tot, inversion_explotacion)+
  labs(title = "Inversión",
       subtitle = "Argentina",
       y = "MM USD")

# CUENCA
autoplot(inv_cuenca, inversion_explotacion)+
  labs(title = "Inversión",
       subtitle = "Argentina",
       y = "MM USD")

```
## Precios
```{r}
# TOTAL
autoplot(precios_tot, precio_interno_crudo)+
  labs(title = "Precios crudo",
       subtitle = "Argentina",
       y = "USD/m3")

autoplot(precios_tot, precio_interno_gas)+
  labs(title = "Precios gas",
       subtitle = "Argentina",
       y = "USD/Mm3")



# CUENCA
autoplot(precios_cuenca, precio_interno_crudo)+
  labs(title = "Precio crudo",
       subtitle = "Argentina",
       y = "USD/m3")

autoplot(precios_cuenca, precio_interno_gas)+
  labs(title = "Precio gas",
       subtitle = "Argentina",
       y = "USD/Mm3")

```


# Estacionalidad
## Producción
```{r}
#TOTAL
prod_tot %>%
  gg_season(prod_pet, labels = "both") +
  labs(y = "m3",
       title = "Seasonal plot: oil production")

prod_tot %>%
  gg_season(prod_gas, labels = "both") +
  labs(y = "Mm3",
       title = "Seasonal plot: natural gas production")

prod_tot %>% 
  gg_subseries(prod_pet) +
  labs(y = "m3",
       title = "Producción de crudo")

prod_tot %>% 
  gg_subseries(prod_gas) +
  labs(y = "Mm3",
       title = "Producción de gas")

#CUENC
data_cuenca_time %>%
  gg_season(prod_pet, labels = "both") +
  labs(y = "m3",
       title = "Seasonal plot: oil production")

data_cuenca_time %>%
  gg_season(prod_gas, labels = "both") +
  labs(y = "Mm3",
       title = "Seasonal plot: natural gas production")


```

## Precios
```{r}
#TOTAL
prod_tot %>%
  gg_season(precio_interno_crudo, labels = "both") +
  labs(y = "USD/m3",
       title = "Seasonal plot: oil price")

prod_tot %>%
  gg_season(precio_interno_gas, labels = "both") +
  labs(y = "USD/Mm3",
       title = "Seasonal plot: natural gas price")

prod_tot %>% 
  gg_subseries(precio_interno_crudo) +
  labs(y = "USD/m3",
       title = "Precio de crudo")

prod_tot %>% 
  gg_subseries(precio_interno_gas) +
  labs(y = "USD/Mm3",
       title = "Precio de gas")

#CUENC
data_cuenca_time %>%
  gg_season(precio_interno_crudo, labels = "both") +
  labs(y = "USD/m3",
       title = "Seasonal plot: oil price")

data_cuenca_time %>%
  gg_season(precio_interno_gas, labels = "both") +
  labs(y = "USD/Mm3",
       title = "Seasonal plot: natural gas price")


```

# Lag plot
```{r}
prod_tot %>% 
  # filter(year(fecha)==2017) %>% 
  gg_lag(prod_pet, geom = "point")
```
# Autocorrelación
```{r}
prod_tot %>% ACF(prod_pet) %>%   autoplot()
data_cuenca_time %>% ACF(prod_pet) %>%   autoplot()
```


# STL (Descomposición de la serie temporal)
## Default
```{r}
dcmp_crudo = prod_tot %>% 
  model(stl = STL(prod_pet)) %>% 
  components()

dcmp_crudo %>%
  as_tsibble() %>%
  autoplot(prod_pet, colour="gray") +
  geom_line(aes(y=trend), colour = "#D55E00") +
  geom_line(aes(y=season_adjust), colour = "#0072B2") +
  labs(
    y = "m3/día",
    title = "Producción de crudo"
  )

dcmp_crudo %>% autoplot()

```

```{r}
dcmp_gas = prod_tot %>% 
  model(stl = STL(prod_gas)) %>% 
  components()

dcmp_gas %>%
  as_tsibble() %>%
  autoplot(prod_gas, colour="gray") +
  geom_line(aes(y=trend), colour = "#D55E00") +
  geom_line(aes(y=season_adjust), colour = "#0072B2") +
  labs(
    y = "Mm3/día",
    title = "Producción de gas"
  )

dcmp_gas %>% autoplot()

```
### STL features
```{r}
prod_tot %>% features(prod_pet, feat_stl)
prod_tot %>% features(prod_gas, feat_stl)

data_cuenca_time %>% features(prod_pet  , feat_stl)
data_cuenca_time %>% features(prod_gas  , feat_stl)

data_cuenca_time %>% 
  features(prod_gas  , feat_stl) %>% 
  ggplot(aes(x = trend_strength, y = seasonal_strength_year,
             col = cuenca)) +
  geom_point() 
```

### Moving average
```{r}
prod_tot %>%
 mutate(
    `5-MA` = slider::slide_dbl(prod_pet, mean,
                .before = 2, .after = 2, .complete = TRUE) ) %>% 
  autoplot(prod_pet) +
  geom_line(aes(y = `5-MA`), colour = "#D55E00") +
  labs(y = "m3/dia",
       title = "Produccion crudo") +
  guides(colour = guide_legend(title = "series"))
```
## Smooth STL
```{r}
prod_tot %>%
  model(
    STL(prod_pet ~ trend(window = 7) +
                   season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

prod_tot %>%
  model(
    STL(prod_gas ~ trend(window = 12) +
                   # season(window = "periodic"),
                   season(window = 13),
    robust = TRUE)) %>%
  components() %>%
  autoplot()
```



# Prophet
```{r}
# library(cowplot)

for (span in c(0.25, 0.5, 0.75, 0.99)){
  loess=stats::loess(prod_pet~as.numeric(fecha), data = prod_tot, na.action = 'na.exclude',
                   model = T, span=span)
  prod_tot['loess_prodpet'] =  predict(loess,prod_tot)
  loess_1 = ggplot(prod_tot, aes(fecha,prod_pet)) + geom_point() + 
    geom_line(aes(y=loess_prodpet), color='firebrick', size=1) +
    labs(title= paste("LOESS span:", span)) + theme_bw() 
  print(loess_1)
  
} 


```
```{r}

#GAS
prophet_df = prod_tot %>% select(fecha, prod_gas) %>% rename(., ds=fecha, y=prod_gas)

#modelo
prophet_model = prophet()
prophet_model = fit.prophet(prophet_model, prophet_df)

#visualizacion del modelo
plot(prophet_model,fcst=predict(prophet_model, prophet_df)) +theme_bw()
prophet_plot_components(prophet_model, fcst=predict(prophet_model, prophet_df))

```
## Prophet con estacionalidad
```{r}
prophet_season=prophet()
prophet_season=add_seasonality(m=prophet_season, name='trim', period=3, fourier.order = 3)
prophet_season = fit.prophet(m = prophet_season, prophet_df) 

plot(prophet_season,fcst=predict(prophet_season, prophet_df)) +theme_bw()
prophet_plot_components(prophet_season, fcst=predict(prophet_season, prophet_df))


#forecasting
#CRUDO
#preprocesamiento dataset prophet
prophet_df = prod_tot %>% select(fecha, prod_pet) %>% rename(., ds=fecha, y=prod_pet)
prophet_df_train = prophet_df %>% filter(year(ds) <= 2018)
prophet_df_test = prophet_df # %>% filter(year(ds) == 2019)

#modelo
prophet_model = prophet(seasonality.mode = 'multiplicative')
prophet_model=add_seasonality(m=prophet_model, name='sem', period=6, fourier.order = 2)
prophet_model = fit.prophet(prophet_model, prophet_df_train)
future <- make_future_dataframe(prophet_model, periods = 6, freq = 'month')
fcst <- predict(prophet_model, future)
plot(prophet_model, fcst)

ggplot()+
  geom_point(data = fcst, aes(yearmonth(ds), yhat, color = "red"))+
  geom_line(data = prophet_df , aes(ds,y))

#visualizacion del modelo
plot(prophet_model,fcst=predict(prophet_model, prophet_df)) +theme_bw()
prophet_plot_components(prophet_model, fcst=predict(prophet_model, prophet_df))


```
### Predicción prophet
```{r}
cv_base = cross_validation(prophet_season, initial = 2, period = 4, horizon = 6, units = '365 days')
# cv_base = cross_validation(prophet_season, initial = 12, period = 2, horizon = 3,  units = 'days')
cv_base
```
```{r}
cv_base
```

```{r}
performance_metrics(cv_base, rolling_window = 0.25)

```

# Forecasting
```{r}
# library(forecast)
library(fable)

#gas
fit_models <- prod_tot %>%
  select(prod_gas) %>%
  fabletools::model(
    mean = MEAN(prod_gas),
    naive = NAIVE(prod_gas),
    drift = NAIVE(prod_gas ~drift()),
    ets = ETS(prod_gas )

    )

fit_models

fit_models %>% 
  select(ets) %>% 
  report()

fit_models %>% 
  fabletools::forecast(h = 12) %>% 
  # filter(.model == "ets") %>%
  autoplot(prod_tot %>% select(prod_gas), level = NULL) +
  autolayer(
    filter_index(prod_tot, "2018 Jan" ~ .),
    colour = "red"
  )+
  theme(legend.position = "bottom") +
  labs(
    x = "",
    y = "Producción de gas"
  ) +
   guides(colour = guide_legend(title = "Forecast"))
```
```{r}
augment(fit_models)
```

