---
title: "Predicción de producción hidrocarburífera"
output: html_notebook
---

# Librerías y funciones
```{r}
rm(list=ls())
gc()

library(readr)
library(tidyverse)
library(ggplot2)
library(lubridate)

library(tsibble) # formato series de tiempo
library(feasts) #librerías para modelos benchmark y STL
library(fable)
library(fabletools) #decomposition_model
library(forecast) #predicciones
library(prophet)



# columnas de agrupamientos (para producción)
group_cols_prod = c( "anio", "mes", 
                "cuenca", "areayacimiento" , "areapermisoconcesion",
                "clasificacion", "tipo_de_recurso" ,"tipopozo", "tipoextraccion",
                "proyecto"
                # ,"concepto"
                )

# función de agregacion
agregacion <- function(x) {
  x %>% 
    summarise(prod_pet = sum(prod_pet, na.rm = T),
           prod_gas = sum(prod_gas, na.rm = T),
           prod_agua = sum(prod_agua, na.rm = T),
           tef_avg = mean(tef_avg, na.rm = T),
           vida_util_avg = mean(vida_util_avg, na.rm = T),
           inversion_explotacion = sum(inversion_explotacion, na.rm = T),
           inversion_exploracion = sum(inversion_exploracion, na.rm = T),
           precio_interno_crudo = mean(precio_interno_crudo, na.rm = T),
           precio_interno_gas = mean(precio_interno_gas, na.rm = T),
           riesgo_pais = mean(riesgo_pais, na.rm = T)
            )
}

#funcion de producción por día
prod_dia <- function(x){
  x %>%   
  mutate(fecha =  yearmonth(paste(anio, mes, sep="/")) ,
         n_dias = days_in_month(fecha),
         prod_pet = prod_pet/n_dias,
         prod_gas = prod_gas/n_dias,
         prod_agua = prod_agua/n_dias) %>%           # CONVERSION A UNIDADES DIARIAS
  select(-n_dias)
}

```

# Datos
```{r}
#datos originales
data <- read_csv("../data/resultados/dataset_2013a2020.csv", 
    locale = locale(encoding = "ISO-8859-1")) %>%
  filter(anio %in% c(2013:2020)) %>%                     # filtro años para mayor velocidad
  prod_dia()
  # group_by_at(group_cols_prod ) %>% 
  # agregacion()


#DATOS DE PRODUCCION
data_time <-  read_csv("../data/resultados/produccion_2013a2020_corregido.csv",
                       locale = locale(encoding = "ISO-8859-1")) %>%
  filter(anio %in% c(2013:2020)) %>%
  prod_dia()

# agregados por cuenca
data_cuenca_time = data %>% 
  distinct(fecha, cuenca,areayacimiento, areapermisoconcesion, .keep_all = T ) %>%
  group_by(fecha, cuenca ) %>%
  agregacion() %>% 
  as_tsibble(index = fecha, 
             key =  cuenca)

rm(data) #limpiamos la memoria
gc()


# agregacion totales por mes
prod_tot = data_time %>%   #NO SIRVE PARA INVERSION ni PRECIOS
  group_by(fecha,anio,mes) %>%  
  summarise(prod_pet = sum(prod_pet, na.rm = T),
           prod_gas = sum(prod_gas, na.rm = T),
           prod_agua = sum(prod_agua, na.rm = T),
           tef_avg = mean(tef_avg, na.rm = T),
           vida_util_avg = mean(vida_util_avg, na.rm = T)) %>% 
  as_tsibble(index = fecha)

#dataset para prophet}
precios_tot = data %>%
  distinct(fecha, cuenca, .keep_all = T ) %>%
  group_by(fecha) %>%
  agregacion() %>%
  as_tsibble(index = fecha)

inv_tot = data %>%
  distinct(anio, concepto,  areapermisoconcesion, .keep_all = T ) %>%
  group_by(anio) %>%
  agregacion() %>%
  as_tsibble(index = anio)

prophet_df = prod_tot %>%
  left_join(precios_tot %>% select(fecha, precio_interno_crudo ,precio_interno_gas),
            by = "fecha") %>% 
  left_join(inv_tot %>% select(anio, inversion_explotacion, inversion_exploracion),
            by = "anio") %>% 
  select(fecha, prod_pet, precio_interno_gas,
         inversion_explotacion, precio_interno_crudo) %>%
  ungroup() %>% 
  mutate(precio_interno_crudo = lag(precio_interno_crudo, k=1)) %>% 
  rename(., ds=fecha, y=prod_pet) %>% 
  na.omit()
  


head(prod_tot)
head(data_time)
head(data_cuenca_time)
  
```

# EDA
## Producción
```{r}
# TOTAL
autoplot(prod_tot, prod_pet)+ #autoplot permite graficar series de tiempo
  labs(title = "Producción de petróleo crudo",
       subtitle = "Argentina",
       y = "m3/d")

autoplot(prod_tot, prod_gas)+
  labs(title = "Producción de gas natural",
       subtitle = "Argentina",
       y = "Mm3/d")

# CUENCA
autoplot(data_cuenca_time, prod_pet)+
  labs(title = "Producción de petróleo crudo",
       subtitle = "Argentina",
       y = "m3/d")+theme(legend.position = "bottom")

autoplot(data_cuenca_time, prod_gas)+
  labs(title = "Producción de gas natural",
       subtitle = "Argentina",
       y = "Mm3/d")


```

### Estacionalidad
```{r}
#TOTAL
prod_tot %>%
  gg_season(prod_pet, labels = "both") +
  labs(y = "m3/d",
       title = "Estacionalidad de producción de crudo")

prod_tot %>%
  gg_season(prod_gas, labels = "both") +
  labs(y = "Mm3/d",
       title = "Estacionalidad de producción de crudo gas natural")

prod_tot %>% 
  gg_subseries(prod_pet) +
  labs(y = "m3/d",
       title = "Producción de crudo")

prod_tot %>% 
  gg_subseries(prod_gas) +
  labs(y = "Mm3/d",
       title = "Producción de gas")



```


# Descomposición de la serie temporal (STL)
```{r}
window_t = 4
window_s = 5

#CRUDO
for (window_t in c(15, 10,8,6,4)){
  stl_smooth = prod_tot %>%
    model(
      STL(prod_pet ~ 
            trend(window = window_t) + #ventana de tendencia
            season(window =window_s) #ventana de estacionalidad
          # season(window = "periodic") # estacionalidad constante a lo largo de los años
      ,robust = TRUE))%>% #parámetro para controlar la robustez
    components() 
  
  print(stl_smooth%>%
    autoplot() )
}

# stl_smooth %>% 
#   # model(NAIVE(season_adjust)) %>%
#   forecast() %>% 
#   autoplot(stl_smooth)
```



```{r}
#GAS
for (window_s in c(17,13,8,5,3)){
print(prod_tot %>%
  model(
    STL(prod_gas ~ trend(window = window_t) +
                   # season(window = "periodic"),
                   season(window = window_s),
    robust = TRUE)) %>%
  components() %>%
  autoplot() )
}
```
# Forecasting
```{r}
prod_train = prod_tot %>% filter(year(fecha)<=2019)
prod_test = prod_tot %>% filter(year(fecha)==2020)

```

## Modelos Benchmark
```{r}
#CRUDO
fit_models <- prod_train %>%
  # select(prod_pet) %>%
  model(
    mean = MEAN(prod_pet),
    naive = NAIVE(prod_pet),
    season_naive = SNAIVE(prod_pet),
    drift = NAIVE(prod_pet ~drift())
    
    )

#forecast
models_fc = fit_models %>% 
  forecast(new_data = prod_test)

models_fc %>% 
  autoplot(prod_train, level = NULL)+
  autolayer(prod_test, prod_pet, colour = "darkblue") +
  labs(y = "m3/dias",
       title = "Producción de crudo",
       subtitle = "Observado y predicho") +
  guides(colour = guide_legend(title = "Forecast"))



```

```{r}
#GAS
fit_models <- prod_train %>%
  select(prod_gas) %>%
  model(
    # stl = STL(prod_gas),
    mean = MEAN(prod_gas),
    naive = NAIVE(prod_gas),
    season_naive = SNAIVE(prod_gas),
    drift = NAIVE(prod_gas ~drift())

    )

fit_models

#forecast
models_fc = fit_models %>% 
  forecast(new_data = prod_test)

models_fc %>% 
  autoplot(prod_train, level = NULL)+
  autolayer(prod_test, prod_gas, colour = "darkblue") +
  labs(y = "Mm3/dias",
       title = "Producción de gas",
       subtitle = "Observado y predicho") +
  guides(colour = guide_legend(title = "Forecast"))


```

## STL
```{r}
#modelo
window_t = 15
window_s = 7

# CRUDO
fit_dcmp <- prod_train %>%
  #hay que expresar la formulación de la descomoposición
  model(stlf = decomposition_model(
    STL(prod_pet ~  trend(window =window_t)+ season(window=window_s)
        ,robust = TRUE),
    NAIVE(season_adjust)
  ))

# fit_dcmp %>%
#   components() %>%
#   autoplot()


#predicción
fit_dcmp_fc <- fit_dcmp %>%
  forecast(new_data = prod_test) 

fit_dcmp_fc%>%
  autoplot(prod_tot)+
  labs(y = "m3/d",
       title = "Pronostico de producción de crudo",
       subtitle = "STL")
```
```{r}
# GAS

fit_dcmp <- prod_train %>%
  model(stlf = decomposition_model(
    STL(prod_gas ~  trend(window =window_t)+ season(window=window_s)
        ,robust = TRUE),
    NAIVE(season_adjust)
  ))


fit_dcmp_fc <- fit_dcmp %>%
  forecast(new_data = prod_test) 

fit_dcmp_fc%>%
  autoplot(prod_tot)+
  labs(y = "Mm3/d",
       title = "Pronostico de producción de gas",
       subtitle = "STL")

```



## Prophet
```{r}

#CRUDO
anio_train_hasta = 2018
anio_test = 2019

# Split train test
prophet_df_train = prophet_df %>% filter(year(ds) <= anio_train_hasta)
prophet_df_test = prophet_df 

#especificación del modelo
prophet_model = prophet( changepoint.prior.scale = 0.5, 
                         # changepoints = c('2014-01-01'),
                         yearly.seasonality=T)#, seasonality.mode = 'multiplicative')
prophet_model = add_regressor(prophet_model,"precio_interno_crudo" ) #agrega regresores
prophet_model = add_regressor(prophet_model,"inversion_explotacion", 
                              mode='multiplicative' )

prophet_model=add_seasonality(m=prophet_model, name='SEM', period=7, fourier.order = 2) #agrega estacionalidad
prophet_model = fit.prophet(prophet_model, prophet_df_train)

#predicciones
future <- make_future_dataframe(prophet_model, periods = 12, freq = 'month')

future$precio_interno_crudo =  prophet_df[year(prophet_df$ds)<=anio_test,]$"precio_interno_crudo" #creo las variabbles regresoras en el dataset a predecir
future$inversion_explotacion = prophet_df[year(prophet_df$ds)<=anio_test,]$"inversion_explotacion"

fcst <- predict(prophet_model, future) #predicción

#visualizacion del modelo
plot(prophet_model, fcst) + add_changepoints_to_plot(prophet_model)

ggplot()+
  geom_point(data = fcst, aes(yearmonth(ds), yhat, color = "red"))+
  geom_line(data = prophet_df %>% filter(year(ds) <=anio_test) , aes(ds,y))

# plot(prophet_model,fcst=predict(prophet_model, prophet_df)) +theme_bw()
prophet_plot_components(prophet_model, fcst=predict(prophet_model, prophet_df))


```



# Errores de predicción
```{r}
accuracy(models_fc, prod_test)
accuracy(fit_dcmp_fc, prod_test)
```


```{r}
#RMSE
sum(((fcst %>% slice(c(85:nrow(.))))$yhat - prophet_df_test$y)^2)
regressor_coefficients(prophet_model)
```
